#terraform import google_cloud_run_v2_service.aggregation-application europe-west1/aggregation-application
#terraform import google_cloud_scheduler_job.aggregation-scheduler europe-west1/aggregation-schedule
#terraform import google_pubsub_topic.aggregation-signals projects/ddd-vienna-sample/topics/aggregation-signals