name: aggregation
concurrency: aggregation-${{ github.ref }}

on:
  workflow_dispatch:
#  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aggregation
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.313"

      - run: dotnet tool restore

      - run: dotnet restore
        name: Restore
        working-directory: ./aggregation

      - run: dotnet build Aggregation.sln --no-restore
        name: Build
        working-directory: ./aggregation

      - run: dotnet test --no-build
        name: Test
        working-directory: ./aggregation
