name: forwarding
concurrency: forwarding-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    paths:
      - "forwarding/"
      - "aggregation/src/Contracts"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: forwarding
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.313"

      - run: dotnet tool restore

      - run: dotnet restore
        name: Restore
        working-directory: ./forwarding

      - run: dotnet build Forwarding.sln --no-restore
        name: Build
        working-directory: ./forwarding

      - run: dotnet test --no-build
        name: Test
        working-directory: ./forwarding